before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
bundler_args: --quiet
script:
  - bundle exec rake test_app
  - bundle exec rspec
language: ruby
rvm:
  - 2.2.3
  - 2.2.4
before_install: gem install ruby_dep -v 1.2.0